### ISSUE TITLE
Script compile error when upgraded from 1.10.3 to 2.x.x

### ISSUE THREAD

**Issue by blufish1234** [lilxyzw/lilToon#310]
There's a script compile error as follow: 
```
Assets\Surin\Tools\lilToon Bulk Copier\Editor\lilToonBulkCopier.cs(8,7): error CS0246: The type or namespace name 'lilToon' could not be found (are you missing a using directive or an assembly reference?)
```
